# Generated by Django 3.1.14 on 2022-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='Brand', max_length=255)),
                ('product_max_price', models.CharField(default='', max_length=255)),
                ('product_discount_price', models.CharField(default='', max_length=255)),
                ('product_description', models.TextField(default='')),
                ('product_long_description', models.TextField()),
                ('in_stock_total', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
