# Generated by Django 3.1.14 on 2022-06-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
